#!/usr/bin/env python

import argparse
import textwrap

# ----------------------------------------------------------------------------
#
# parse command line options
#
# ----------------------------------------------------------------------------
desc = """A tool that generates pantheon reports
"""

parser = argparse.ArgumentParser(
                    formatter_class=argparse.RawDescriptionHelpFormatter,
                    description=textwrap.dedent(desc)
                    )

parser.add_argument( "--sourcedir", required=True, default=None, 
                     help="directory where Pantheon results are")
parser.add_argument( "--output", required=True, default=None, 
                     help="file where report is written")

args = parser.parse_args()

# print("sourcedir: {}".format(args.sourcedir))
# print("output:    {}".format(args.output))


#
# do the work
#
# ----------------------------------------------------------------------------


# look for information in the sourcedir

datetime = "Some date and time"
with open(args.output, 'w') as outfile:
    outfile.write("# Pantheon Report\n")
    outfile.write("Date: {}\n".format(datetime))
