#!/usr/bin/bash

echo "Running Pantheon report Script"

exampledir=pantheon-report/workflows/
workdir= 'pantheon-report'
mkdir $workdir
pushd $workdir

git clone git@github.com:pantheonscience/ECP-E4S-Examples.git workflows

pushd EC
git sibmodule update --init --recursive
popd
popd

#copy pantheon bootstrap
exampledir='pantheon-report/workflows/Ascent-miniapp-example'
cp bootstrap.env $exampledir

#run all the workflows
pushd $exampledir
#./execute

#collect data
source pantheon.env.sh
echo $PANTHEON_WORKFLOW_DIR
ls $PANTHEON_WORKFLOW_DIR

#./pantheon_report --sourcedir $PANTHEON_WORKFLOW_DIR --output report.md
